applications/README.md
No parent issue, as it's a very quick fix. I was sending the documentation to someone and realized this new syntax was missing from the docs.
=> Describe inputs and outputs in application syntax

python/src/aica_api/client.py
- #14 
This PR solves the issue by changing the endpoint to v1.
=> Update Python API client to use new v1 endpoints

schemas/applications/schema/application.schema.json, schemas/applications/schema/buttons.schema.json, schemas/applications/schema/components.schema.json, schemas/applications/schema/position.schema.json
- #23 
This PR solves the issue by adding component position and buttons to application schema.
=> Add component position and buttons to application schema

.github/workflows/generate-ts-declaration.yml
- https://github.com/aica-technology/modulo-controllers/issues/88
Small task in the parent epic. I didn't convert it to an issue because it's now a very simple change thanks to our workflow.
=> Generate TypeScript declaration for controller schema in workflow

schemas/component-descriptions/README.md, schemas/component-descriptions/schema/component.schema.json
- #29 
In advance of the release, and as I have been refactoring how schemas are handled across the API and frontend, I think it's a good time to make this simplification. See the parent issue for context.
=> Simplify component registration

.github/workflows/publish-to-pypi.yml, python/pyproject.toml
- #37 
Deploy python API client to PyPi automatically when on push to main, develop, or on a version tag, and only on changes to the `python` path.
An example of the workflow: https://github.com/aica-technology/api/actions/runs/5748364572
=> Deploy python API client to PyPi automatically

python/pyproject.toml, python/src/aica_api/client.py
- #9 
This PR adds a new endpoint: get_application_state
=> Include get_application_state endpoint in Python client

schemas/applications/schema/application.schema.json
- [#350](https://github.com/aica-technology/frontend/issues/350)
This PR solves the issue by adding position to on_start in application schema.
Estimated Time of Review: 1 minutes
=> Add position to on_start in application schema

python/pyproject.toml, python/src/aica_api/client.py
Add a missing method to set parameters on components
=> Add set_parameter to API client

schemas/applications/README.md, schemas/applications/schema/common/log_level.schema.json, schemas/applications/schema/components.schema.json, schemas/applications/schema/hardware_interfaces.schema.json
- #33 
This PR solves the issue by putting the log level schema into the common folder and reuse it in both the component and hardware interfaces schema.
=> Add controller log level to the application schema

schemas/applications/schema/buttons.schema.json
- https://github.com/aica-technology/frontend/issues/345
This PR extends the event type for the trigger event button to support all event types.
=> feat: extend trigger event button's event type

.github/workflows/generate-ts-declaration.yml, .github/workflows/publish-to-pypi.yml
This PR updates the ci workflow before fast forward to `main` and delete the `develop` branch.
Estimated Time of Review: 1 minutes
=> ci: update workflow before deleting develop branch

python/src/aica_api/client.py
Review by commit. They address each change in the backend-api separately:
1. https://github.com/aica-technology/backend-api/pull/115
2. https://github.com/aica-technology/backend-api/pull/112
3. https://github.com/aica-technology/backend-api/pull/111
4. https://github.com/aica-technology/backend-api/pull/116
=> refactor!: update python client to match backend API

python/src/aica_api/client.py
- #55 
This PR updates the `check()` function to check if the API version is at least v2.
=> fix: update check function

.github/workflows/publish-to-pypi.yml, python/pyproject.toml
- #57 
This PR solves the issue by using `check-version` action to check if the `push-to-pypi` is needed.
=> ci: check pyproject version before push

python/CHANGELOG.md, python/pyproject.toml
- #65 
This PR solves the issue by updating the version.
=> release: version 1.0.0 for python client

schemas/applications/schema/components.schema.json, schemas/applications/schema/events/call_service.schema.json, schemas/applications/schema/events/identifiers/hardware.schema.json, schemas/applications/schema/events/identifiers/load_unload_target.json, schemas/applications/schema/events/lifecycle.schema.json, schemas/applications/schema/events/load.schema.json, schemas/applications/schema/events/set.schema.json, schemas/applications/schema/events/switch_controllers.schema.json, schemas/applications/schema/events/unload.schema.json, schemas/applications/schema/hardware.schema.json
Before tagging version 1 of this schema I wanted to clean up a few things. Mostly, it is about better typescript generation. The schema provides options for names and descriptions. In typescript generation with `json-schema-to-typescript`, each named property is exported as a new interface, while "anonymous" properties are just defined inline. If there are multiple properties with the same name, it will append a number to distinguish the duplicates. And, if a schema is too complex to be represented in typescript, it will be represented as the `unknown` type.
Change type 1: adding a name to a sub property (for example, the load / unload property, the lifecycle object and the service object).
Change type 2: adding a name to a sub property to avoid duplication (for example, the …
=> Refactor property names in schema

docs/static/schemas/application.schema.json, docs/static/schemas/component.schema.json, docs/static/schemas/controller.schema.json
continue https://github.com/aica-technology/api/pull/74
Manually add 1-0-0 schema. See comment here: https://github.com/aica-technology/api/pull/74#issuecomment-1812070257
Estimated Time of Review: 1 minutes
=> docs: schema versions 1-0-0

docs/static/schemas/1-0-0/application.schema.json, schemas/parameters/schema/encoded_state_type.schema.json, schemas/parameters/schema/parameter.schema.json, schemas/parameters/schema/parameter_type.schema.json, schemas/signals/schema/signal.schema.json, schemas/signals/schema/signal_type.schema.json, utils/bundleHelper.js
- #78 
I update the `bundleHelper.js` to avoid some symbols being replaced. Also remove the old "id" I found in other files.
=> fix: bundling issues with application schema

python/CHANGELOG.md, python/src/aica_api/client.py
Quick fix to an issue reported by @domire8:
> I have a problem with setting component parameters... if i do it through the Swagger UI page, I get:
```
127.0.0.1 - - [05/Dec/2023:13:40:12 +0000] "PUT /v2/application/components/orbiter/parameter/speed_scale HTTP/1.1" 202 0 "http://localhost:5000/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0"
```
> If I do `set_component_parameter("orbiter", "speed_scale", "0.0")` from another container with the python API client I get:
```
127.0.0.1 - - [05/Dec/2023:13:39:40 +0000] "PUT /v2/application/components/orbiter/parameter/speed_scale HTTP/1.1" 400 156 "-" "python-requests/2.31.0"
```
This PR solves the issue by changing the JSON payload from `{"parameter_value": ...}` to `{"value": ...}` as per the new v2 API …
=> fix(client): json format for setting parameter value

python/CHANGELOG.md, python/pyproject.toml, python/src/aica_api/client.py
A small feature that I didn't realize was missing until requested by @domire8, this adds the endpoint to set lifecycle transitions.
It also tags a new minor release v1.1.0 which includes the fix from #80.
=> feat(client): support lifecycle transition

docs/docs/reference/02-yaml-syntax.md, schemas/applications/README.md, schemas/component-descriptions/README.md
- https://github.com/aica-technology/backend/issues/121
Small comment should be enough.
=> docs: add instructions for YAML validation with VS code

python/CHANGELOG.md, python/pyproject.toml, python/src/aica_api/client.py
- #89 
This issue suggests that we could log something, that would be 'new' for this client though. Should we just use `print()`?
=> feat: parse yaml file if it exists

docs/static/schemas/1-1-0/application.schema.json
This PR adds the 1-1-0 application schema manually because of the previous workflow failed
=> docs: add 1-1-0 application schema manually

schemas/component-descriptions/CHANGELOG.md, schemas/component-descriptions/README.md, schemas/component-descriptions/schema/component.schema.json, schemas/controller-descriptions/CHANGELOG.md, schemas/controller-descriptions/schema/controller.schema.json, schemas/parameters/schema/parameter.schema.json
- #99 
See parent issue for the discussion. The changes a schema are: `If the default value of a parameter is set to anything different from null, the property optional is prohibited`
=> feat(parameter-schema): add new keyword optional for the parameter schema

docs/docs/reference/02-yaml-syntax.md, schemas/applications/CHANGELOG.md, schemas/applications/schema/application.schema.json, schemas/applications/schema/conditions.schema.json
- #112 
This PR solves the issue by tweaking the conditions schema such that the parser (and the user) know which properties are allowed on the top level, and then the recursion only starts one level deeper. It is a bit of code duplication but still quite an elegant solution IMO. Tested especially in the DSE, so I'm quite confident this is good to go.
=> fix: update conditions schema

README.md
Just a little addition to the README to bundle schemas locally, thanks to @jjenscodee for showing me.
=> feat: add readme section for bundling schemas

docs/docs/getting-started/05-examples/03-mock-hardware-example.md
- #0
This PR solves the issue by ...
Estimated Time of Review: 1 minutes
=> docs(getting-started): add rate to example to conform w/ syntax checks

docs/docs/getting-started/02-licensing.md, docs/docs/getting-started/03-installation.md, docs/docs/getting-started/05-examples/01-timer-example.md, docs/docs/getting-started/05-examples/03-mock-hardware-example.md
=> docs: update packaging instructions and base version

python/CHANGELOG.md, python/README.md, python/pyproject.toml
Separate release PR to keep the changes cleaner (release notes, changelog)
Estimated Time of Review: x minutes
- #95
=> release(client): v2.0.0

README.md, docs/docs/reference/02-yaml-syntax.md, schemas/applications/CHANGELOG.md, schemas/applications/schema/application.schema.json, schemas/applications/schema/events/lifecycle.schema.json
- #117 
This PR solves the issue by allowing simple transition keywords again
=> feat(application-schema): allow lifecycle objects to be just the transition keyword

README.md, docs/docs/reference/02-yaml-syntax.md, docs/docs/reference/custom-components/02-custom-component.md
- #132 
This PR solves the issue by fixing the import.
- [N/A ] Confirm that the relevant changelog(s) are up-to-date in case of any user-facing changes
=> doc: fix incorrect clproto import in example

docs/docs/reference/02-yaml-syntax.md
- #129 
This PR solves the issue by describing the sequencing syntax introduced in application schema 1-2-0. I also re-structured the YAML syntax page to present a bit more of a logical order.
This is a draft for now until the base image release 3.1.0 is out.
Estimated Time of Review: x minutes
=> docs(yaml): describe sequences

docs/docs/getting-started/03-installation.md, docs/docs/getting-started/05-examples/01-timer-example.md, docs/docs/getting-started/05-examples/03-mock-hardware-example.md, docs/docs/reference/custom-components/04-package-building.md, docs/docs/reference/custom-components/05-aica-package-toml.md
This PR updates the tags of the versions used in the examples of the docs. Mainly triggered by the fact that v3.0.0 of the base is incompatible with v3.0.4 of ur-collections.
=> fix(docs): update version tags in examples

docs/docs/reference/custom-components/02-custom-component.md
- #139 
This PR solves the issue by adding a caution block to the relevant section
=> feat: add note about signal name conventions

docs/docs/reference/02-yaml-syntax.md, schemas/applications/CHANGELOG.md, schemas/applications/schema/application.schema.json, schemas/applications/schema/components.schema.json, schemas/applications/schema/hardware.schema.json, schemas/component-descriptions/schema/component.schema.json, schemas/controller-descriptions/CHANGELOG.md, schemas/controller-descriptions/schema/controller.schema.json, schemas/predicates/schema/predicate.schema.json, schemas/services/schema/service.schema.json
- #145 
This PR solves the issue by adding controller predicates to controller descriptions and predicates for controllers to the application schema. They are both released with new minor versions.
=> feat: add predicates to controller and application schemas

docs/static/schemas/1-3-0/controller.schema.json, docs/static/schemas/1-4-0/application.schema.json, schemas/applications/schema/hardware.schema.json
- https://github.com/aica-technology/api/actions/runs/8752660355
The one time I don't test my changes..
Estimated Time of Review: 1.1 minutes
=> fix: application schema 1-4-0 and controller schema 1-3-0

docs/static/schemas/1-4-0/application.schema.json, schemas/applications/schema/hardware.schema.json
After #146 introduced controller events to the application schema with a missing closing bracket, #148 "fixed" this problem but added the closing bracket in the wrong place. As a result, the required properties were nested _under_ the controller and hardware properties, rather than being next to them.
Overly simplified view of how the incorrect nesting for required properties looked after #148:
```
hardware: {
properties: {
controllers: {
properties: {
events: {
...
},
required: [ ],
},
},
required: [ ]
}
}
```
Overly simplified view of how the correct nesting for required properties should look (fixed in this PR):
```
hardware: {
properties: {
controllers: {
properties: {
events: {
...
}
},
required: [ ],
}
},
required: [ ]
}
```
Since the previous deployment of schema 1-4-0 failed to …
=> fix: invalid nesting of required properties in schema 1-4-0

python/CHANGELOG.md, python/pyproject.toml
A bit late but after testing the previous 2.1.0 release candidate (https://pypi.org/project/aica-api/2.1.0rc1/) it's now time to release 2.1.0 properly.
=> release(client): v2.1.0

schemas/applications/CHANGELOG.md, schemas/applications/schema/application.schema.json, schemas/applications/schema/buttons.schema.json
- Part of https://github.com/orgs/aica-technology/projects/1/views/24?pane=issue&itemId=69008373
This PR adds the `set_parameter` to buttons on_click.
=> feat(schema): allow set_parameter in buttons

.github/ISSUE_TEMPLATE/BUG-REPORT.yml, docs/docs/getting-started/03-installation.md, docs/docs/getting-started/05-examples/01-timer-example.md, docs/docs/getting-started/05-examples/03-mock-hardware-example.md, docs/docs/reference/custom-components/04-package-building.md, docs/docs/reference/custom-components/05-aica-package-toml.md, docs/docs/reference/custom-components/06-aica-package-migrations.md
* Update all documentation referring to the old syntax of the builders
* Add a page to help migrate from the old version of `package-builder` (I didn't add one for `app-builder` because the changes are so small)
* Added more in-depth section about version constraints
=> docs: update documentation for the version of the builders

schemas/component-descriptions/CHANGELOG.md, schemas/component-descriptions/schema/component.schema.json
- #168 
This PR solves the issue by adding a new optional property that marks if a component is a lifecycle component.
Followup steps would be to define this property in the description of the lifecycle component in modulo 5.0, so that it can be inherited for all subsequent properties.
=> feat(schema): add lifecycle property to component description

docs/static/schemas/draft/2-0-0/application.d.ts, docs/static/schemas/draft/2-0-0/application.schema.json, schemas/applications/CHANGELOG.md, schemas/applications/README.md, schemas/applications/schema/common/events/call_service.schema.json, schemas/applications/schema/common/events/lifecycle.schema.json, schemas/applications/schema/common/events/set.schema.json
- #167 
Here, I enforce lifecycle, parameter and service events to include a target component as per the issue description. I also removed a legacy "string" type structure for call service which used to allow `call_service: foo` instead of `call_service: { service: foo }`.
I already updated the changes to the generated schemas in the docs/static directory as part of this PR, since the version hasn't changed. Normally we are not allowed to manually update the static deployments for backwards compatibility reasons, but here the `draft` path is intended to allow us to make these breaking changes for downstream testing before the official release.
=> feat(schema): remove self targeting events

docs/static/schemas/draft/2-0-0/application.d.ts, docs/static/schemas/draft/2-0-0/application.schema.json, schemas/applications/schema/graph.schema.json, schemas/applications/schema/hardware.schema.json
After testing, this adds a field for the position of the "stop" node in the application graph. It also removes the "on_rate_violation" event trigger from the hardware, as it was decided that this is not really a transition event. Instead, rate errors will simply be part of the on_error transition for hardware in strict mode.
I regenerated the typescript declaration for the draft, which I didn't do in the last PR, so that file has more apparent changes.
=> feat(schema): minor schema revisions for draft/2-0-0

docs/static/schemas/draft/2-0-0/application.d.ts, docs/static/schemas/draft/2-0-0/application.schema.json, schemas/applications/CHANGELOG.md, schemas/applications/schema/hardware.schema.json
This adds display name field to the controller property of hardware, to allow controllers to be renamed if desired.
- #174
=> feat(schema): add controller display name

docs/static/schemas/draft/2-0-0/application.d.ts, docs/static/schemas/draft/2-0-0/application.schema.json, schemas/applications/CHANGELOG.md, schemas/applications/README.md, schemas/applications/schema/application.schema.json
This was missed in all of the recent renaming. Thanks @LouisBrunner for catching it!
=> feat(schema): rename base to core

docs/static/schemas/draft/2-0-0/application.d.ts, docs/static/schemas/draft/2-0-0/application.schema.json, schemas/applications/CHANGELOG.md, schemas/applications/schema/common/condition_object.schema.json, schemas/applications/schema/components.schema.json
After in-depth testing of the new syntax, the following revisions have been made here:
- include additional lifecycle transition events for components for error management
- use the correct state for controllers in condition sources ("inactive" instead of "loaded")
- include missing sequence state in condition sources (aborted)
As usual with this draft schema, I'm directly updating the static generated files.
=> feat(schema): revise transitions and states

schemas/applications/schema/application.schema.json
- #147 
Setting the application schema version from `draft/2-0-0` should trigger the corresponding CI actions to bundle and release this version!
=> release(schema): application schema 2-0-0

schemas/applications/CHANGELOG.md, schemas/applications/schema/application.schema.json
This patch replaces the version constraint regex for the package dependencies with a simpler and more permissive case.
The previously used regex lookaround expressions were not supported in all browsers, including Safari.
=> fix(schema): replace regex lookaround with more permissive case

docs/docs/getting-started/04-examples/03-mock-hardware-example.md, docs/docs/reference/custom-components/04-package-building.md
After #166, I accidentally left in some links to the now deleted page. This prevents the site from building and being deployed. I updated the sections accordingly.
=> fix(docs): replace outdated links with updated instructions

schemas/applications/CHANGELOG.md, schemas/applications/schema/application.schema.json, schemas/applications/schema/buttons.schema.json
As requested by @domire8, this minor addition allows application events (namely, `application: stop`) to be included under graph button events.
=> feat(schema): include application events under graph button events

docs/docs/concepts/03-ros-concepts/04-control.md, docs/docs/concepts/05-building-blocks/02-events.md, docs/docs/getting-started/01-intro.md
This PR updates a few lines in the docs that required a bit more precision.
=> docs: minor improvements

schemas/applications/CHANGELOG.md, schemas/applications/schema/components.schema.json
This PR adds intra process comms field to components in the application schema. I don't know if we should directly go for 2-0-3 or if it might be helpful to have a draft 2-0-3.
=> feat(schema): add intra process comms field to component schema

docs/docs/reference/custom-components/04-package-building.md, docs/docs/reference/custom-components/05-aica-package-toml.md
An update here to correct the outdated tags in parts of the docs
=> docs: update to more recent tags

docs/docs/getting-started/02-licensing.md, docs/docs/getting-started/03-installation-and-launch.md, docs/docs/getting-started/04-examples/03-mock-hardware-example.md, docs/docs/reference/02-manual-installation-launch.md, docs/docs/reference/03-yaml-syntax.md, docs/docs/reference/custom-components/01-component-package.md, docs/docs/reference/custom-components/_category_.json
In this PR, I'm bringing back the installation and launch sections that we had before the launcher (removed in #166). I think this is still very valid information, and I refer to it a lot. Especially in headless mode where people ssh into an IPC this is still relevant. I updated just the versions to the latest tags, but I need some help checking that the docker run instructions are still correct with the port mapping and so on @LouisBrunner 
=> docs: bring back manual installation and launch

.github/workflows/bundle-schema.yml
I forgot something in #202 after all :roll_eyes: I just forgot to copy it over from the test fork. Missing checkout action after splitting the workflow into separate jobs.
=> fix: missing checkout action

docs/docs/reference/custom-components/03-component-descriptions.md
- https://github.com/aica-technology/api/actions/runs/12709048528/job/35427263510
This PR fixes links that were broken in #202.
=> fix(docs): schema links

docs/docs/getting-started/04-examples/01-timer-example.md, docs/docs/getting-started/04-examples/02-editor-example.md
Wanted to center the images, do you know if this is going to work? According to [this](https://tw-docs.com/docs/static-site-generators/docusaurus-image-center/) it should
=> fix(docs): center images

python/CHANGELOG.md, python/examples/with_api_key.py, python/pyproject.toml, python/src/aica_api/client.py, python/src/aica_api/sio_client.py
Resolves https://github.com/aica-technology/core-backend/issues/400
Changes:
* Added a new `api_key` argument in the constructor
* The client should still work the same if the user isn't using a `api_key`
* Otherwise we will automatically create and renew the auth token using the key
* Also added URL encoding for all path arguments
* Added a small example for testing and demonstration
* Code was formatted by Ruff
=> feat(python): add support for the upcoming auth update

schemas/applications/CHANGELOG.md, schemas/applications/schema/application.schema.json, schemas/applications/schema/joint_positions.schema.json
- https://github.com/aica-technology/core-backend/issues/423
This PR adds `joint_positions` to the application schema such that applications can define static joint configurations to be consumed by components and controllers.
=> feat(schema): add joint positions to application schema

docs/docusaurus.config.js, docs/src/pages/index.module.css, docs/src/pages/index.tsx
As requested by @rrosa24, this adds a link to AICAdemy on the homepage. I also added shortcut buttons to the main docs sections and extended the links in the header and footer.
=> docs: improve links on homepage, header and footer

docs/docusaurus.config.js, docs/src/pages/index.tsx
=> docs: fix aicademy link

schemas/interfaces/CHANGELOG.md, schemas/interfaces/schema/interfaces.schema.json
Here I upgrade the interfaces schema from draft/1-0-0 to 1-0-0. A followup is to update and release the component and controller descriptions to use this new officially versioned common interface (including a small fix needed in the component schema), but that can only be done and released after 1-0-0 has been bundled and pushed.
=> release(schema): interfaces schema 1-0-0

docs/docs/reference/custom-components/03-component-descriptions.md, schemas/component-descriptions/CHANGELOG.md, schemas/component-descriptions/schema/component.schema.json, schemas/component-descriptions/schema/signal_collection.schema.json
This updates the component description schema to use the 1-0-0 common interfaces. It also updates the references in the documentation and fixes one small mistake on the staging branch where `signal_type` was referenced instead of `signal`.
I tested the bundling locally and the only changes are to the signal types as mentioned in the changelog.
=> release(schema): component 1-1-2

schemas/controller-descriptions/CHANGELOG.md, schemas/controller-descriptions/schema/controller.schema.json
This updates the controller description schema to use the 1-0-0 common interfaces. It also fixes one small mistake on the staging branch where signal_type was referenced instead of signal.
I tested the bundling locally and the only changes are to the signal types as mentioned in the changelog.
=> release(schema): controller 1-3-1

.github/ISSUE_TEMPLATE/BUG-REPORT.yml, .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml, .github/ISSUE_TEMPLATE/QUESTION.yml
After this PR, @rrosa24 will be automatically assigned to submitted questions, feature requests, bug reports for visibility
Estimated Time of Review: 1.1 minutes
=> feat: automatically tag rrosa24 on submitted issues

.github/ISSUE_TEMPLATE/BUG-REPORT.yml
This PR changes the Bug Report template to not request for a manifest file (since we're not exposing that anymore) but for a screenshot of the Launcher configuration.
- [N/A ] Confirm that the relevant changelog(s) are up-to-date in case of any user-facing changes
=> feat: update bug report to paste launcher config

.github/workflows/build-docs.yml, docs/docusaurus.config.js, docs/package-lock.json, docs/package.json
- #239 
This PR solves the issue by upgrading our version of Docusaurus from v2.4 to v3.7. I also installed KaTeX for math equation rendering, which is one of the features that works well with v3.
Apart from the changes to the packages and configurations, no other changes are needed, since we didn't use MDX v1 very heavily or have other reasons for breaking changes.
Estimated Time of Review: 15 minutes
Please check if any pages have weird rendering issues.
You will need to do `npm install` before running the dev server. Note that this requires Node >= 18.0 to run dev server or build.
=> feat: upgrade to Docusaurus v3

docs/docs/getting-started/03-installation-and-launch.md, docs/docs/reference/02-manual-installation-launch.md
- #243
This PR solves the issue by updating the installation instructions regarding docker desktop on linux.
=> docs: update installation instructions for docker desktop on linux

schemas/applications/CHANGELOG.md, schemas/applications/schema/application.schema.json
:steam_locomotive: 
This change was mostly motivated by:
1. Frames with captial letters in the UR AI Accelerator kit
2. Parameter names with dots in the Realsense component
=> release(schema): application schema 2-0-4

docs/docs/concepts/05-building-blocks/04-controllers/04-controllers.md, docs/docs/concepts/05-building-blocks/04-controllers/jtc.md
- #273 
This PR solves the issue by adding a short JTC overview in the docs. 
The idea is to provide a short introduction to why a JTC is interesting and some very high level information about how it works.
Ultimately I would link to 1) a few simple examples in #274  and 2) a complete guide on how to set it up on AICA Studio with frame recordings in #275.
=> docs: add JTC overview

docs/.dockerignore, docs/Dockerfile, docs/README.md, docs/docker-compose.yaml, docs/package.json, docs/src/pages/index.tsx
Authored by @LouisBrunner, adds Docker for easy docs development. Split into PR as requested by @domire8.
=> feat(docs): add Docker build for ease of testing

docs/static/schemas/2-0-6/application.schema.json, schemas/applications/schema/common/events/set.schema.json
Unfortunately with #297 I missed one thing during testing.
I previously wrote:
> Validation against this schema works in the VSCode yaml extension and in the ajv library for frontend parsing
This was true for both old and new syntax for parameters on components and controllers, and the new syntax for the "set parameter" event. However, I hadn't tested the `ajv` frontend parser for the case of the old set parameter event (without specifying a type). Despite this case validating fine in VSCode, `ajv` compalins with the following error:
The cause is the combination of the `oneOf` and the `if`/`then` statements for makign state_type conditionally required when `type` is set to `"state"`. I tried to find a way to resolve it while keeping the same logic, but unfortunately I could not make it …
=> fix: remove conditional dependency for SetParameterObject

docs/docs/examples/core-controllers/jtc-example.md, docs/docs/examples/guides/jtc-guide.md
- #319 (also resolves the minor #320)
Here, I am updating the JTC docs to reflect some subtle but potentially breaking (at the payload level) changes. Apart from that, I also took the chance to add some small mentions to `durations`.
Estimated Time of Review: 8 minutes
=> docs: update JTC docs for AICA Core v4.4.2

TERMS_OF_USE.md
This PR adds a Terms of Use document in markdown to clearly define the agreement between AICA and users of AICA software. This document will be referenced in products like AICA Launcher, and may be revised in future.
=> feat: terms of use

docs/docs/getting-started/compatibility/_category_.json, docs/docs/getting-started/compatibility/operating-system.md, docs/docs/getting-started/compatibility/supported-hardware.md, docs/docs/getting-started/installation/_category_.json
This PR restructures the Getting started page of the documentation, adding a new **Compatibility** section with a **Supported hardware** page, that lists supported manufacturers and devices. 
- #336  
=> docs: add hardware compatibility section
