aica-technology/api

applications/README.md

Most of this was taken from the existing README in the state engine. I reformatted and extended it with descriptions of the hardware interfaces and conditions.

Add YAML application syntax documentation

---

python/README.md
python/pyproject.toml
python/src/aica_api/client.py

Upcoming changes to the application API endpoints are intended to increase the clarity of behaviours. The following endpoints are affected: 
- `stop_application` has been renamed to `pause_application`
- `reset_application` has been renamed to `stop_application`

Rename application service endpoints

---

applications/schema/schema/application.schema.json
applications/schema/schema/components.schema.json
applications/schema/schema/conditions.schema.json

To wrap up the schema, here are conditions. It was actually not as bad as I thought to incorporate the recursive logic. A quick summary:
Top-level must have `events` and either `condition_object` or `predicate_object` fields. The predicate object is just an associated component and predicate. The condition object has fields [all, any, one_of, not]. The first three refer to `condition_array` - that is, a list of items which must be either another condition object, predicate object, or bool (for hard-coded conditions). The `not` doesn't take an array of items, but instead just one of condition object, predicate object, or bool.
Here are some valid examples that are validated correctly:
```yaml
conditions:
test_single_predicate:
component: foo
predicate: foo
events:
load: foo …
```

Extend application schema with conditions

---

applications/schema/schema/components.schema.json

- #10
As a small followup to the issue and #11, I remembered that signal collections are also a thing we can eventually support. As with inputs / outputs, the idea is just to append `_topics` to the collection name and set the parameter.
Before:
```yaml
recorder:
component: base_components::data::filesystem::BinaryRecorder
parameters:
recording_directory: /tmp
recordings_topics: [ force_controller/cartesian_state ]
```
After:
```yaml
recorder:
component: base_components::data::filesystem::BinaryRecorder
parameters:
recording_directory: /tmp
input_collections:
recordings: [ force_controller/cartesian_state ]
```
A slightly more complicated option would be to have the `inputs:` field allow either `string` or `string_array` data, then have the YAML parser convert it either to `_topic` or …

Support input collections in YAML schema

---

schemas/component-descriptions/README.md
schemas/controller-descriptions/README.md
schemas/controller-descriptions/schema/controller.schema.json
schemas/parameters/schema/parameter.schema.json

- https://github.com/aica-technology/modulo-controllers/issues/91
Following #20, I also wanted to have the ability to mark inheritance for controllers. However, many of the base parameters in the modulo controller interface are "optional" or only used internally. Derived controllers often will not need to set this, and in general the user-facing parameters should be reduced where possible. The new `internal` property for parameters allows us to mark this behavior and thereby hide some parameters from the user (unless they tick some box to show all parameters for example).
I did it in a separate step because I wanted to add a field to the parameters descriptions, but not introduce too many changes in a single PR.
Up to debate whether `internal` is a good name or something like `advanced` …

Controller inheritance and internal parameters

---

python/pyproject.toml
python/src/aica_api/client.py

Small bug fix after #19, I didn't notice that the websocket endpoint was also changed to have `/v1`. This causes the websocket connection to fail.
Maybe it would actually be a good idea to put the websockets under the v1 namespace also, but for now the websockets are published directly on `/components`, `/conditions` and `/logs`. 
I also finally fixed up the `wait_for_predicate` function, since it was using the long-deprecated `/predicates` websocket which doesn't exist. The new functions were tested with a real application and working as intended.

Fix websocket client

---

schemas/applications/schema/events/set.schema.json

- https://github.com/aica-technology/dynamic-state-engine/pull/151
This PR adds the controller parameters to the `set` event in the schema. Because neither `controller/interface` nor `component` are required, I had to add basically three different objects that are allowed for the `set`. There might be a simpler version that I didn't see but this works and is tested (with vs code)

feat(application schema): add support for setting controller parameters

---

schemas/component-descriptions/schema/component.schema.json
schemas/component-descriptions/schema/predicate.schema.json
schemas/component-descriptions/schema/service.schema.json
schemas/component-descriptions/schema/signal_collection.schema.json
schemas/controller-descriptions/schema/controller.schema.json
schemas/parameters/schema/encoded_state_type.schema.json
schemas/parameters/schema/parameter.schema.json
schemas/parameters/schema/parameter_type.schema.json
schemas/signals/schema/signal.schema.json
schemas/signals/schema/signal_type.schema.json

A necessary patch before #50. This preemptively changes all of the re
Note; using `main` is a temporary solution. The plan is to tag the repository with a version of the schema and then use that instead of the branch name in the URI. That can be done after everything is on main, and perhaps after the API refactor, so that we can properly version the schemas, the API and the python client. 
Estimated Time of Review: 0 minutes

refactor(schema): change schema URIs from develop to main

---

python/CHANGELOG.md
python/pyproject.toml
python/src/aica_api/client.py

The API endpoint was still pointing to v1 🤦 
Estimated Time of Review: 0.1 minutes

fix: use v2 address for endpoints

---

schemas/applications/CHANGELOG.md
schemas/applications/schema/application.schema.json
schemas/applications/schema/conditions.schema.json
schemas/applications/schema/events.schema.json
schemas/applications/schema/events/identifiers/condition.schema.json
schemas/applications/schema/events/identifiers/predicate.schema.json
schemas/applications/schema/events/sequence.schema.json
schemas/applications/schema/sequences.schema.json

- #127 
This PR addresses the issue by defining a sequencing syntax in the application schema.
To validate mutually exclusive fields in `wait` and `assert`, I used a trick with `oneOf`. Because `oneOf` must always validate one and only one subschema, putting `{}` as the first item under `oneOf` always validates first and effectively prohibits all subsequent schemas.
Estimated Time of Review: 20 minutes

feat(schemas): sequences

---

python/CHANGELOG.md
python/README.md
python/pyproject.toml
python/src/aica_api/client.py

- #158 
Check feature and function version compatibility more precisely:
* Use deprecation module to warn deprecated function with version range
* Add helper and local class attribute to get and store api server version
* Define decorator to require a minimum api server version when calling a function, otherwise warn and return None
* Update check() function with more cases
* Use semver module to compare and match versions instead of string comparisons
* Use logging module instead of printing warnings
* build: add and revise dependencies
To test this out properly (since I changed some dependencies), I pushed a release candidate to the test registry at https://test.pypi.org/project/aica-api/2.1.0rc5. As part of this, I learned that doing a pip install from this registry will also try to …

feat(client): define more detailed feature and function compatibility between versions

---

docs/docs/getting-started/04-run.md

This is a small bug in the docs that I have been meaning to fix for a while. Simply, I forgot to include the `-u ros2` flag from the docker exec steps for interactive containers. This means things like `ros2 topic list` and `rviz2` would not work exactly as expected. In particular, rviz2 would not see any TFs.
- [NA] Confirm that the relevant changelog(s) are up-to-date in case of any user-facing changes

docs: add -u ros2 to docker exec guide

---

docs/static/schemas/draft/2-0-0/application.d.ts
docs/static/schemas/draft/2-0-0/application.schema.json
schemas/applications/CHANGELOG.md
schemas/applications/README.md
schemas/applications/schema/application.schema.json
schemas/applications/schema/buttons.schema.json
schemas/applications/schema/graph.schema.json

The ability to support sequence events by clicking UI buttons was still missing from the draft, as raised by @yrh012. Additionally, after some discussions I decided to move `buttons` property under the new `graph` section of the YAML, since they are pure UI features that have no other impact on the application structure.

feat!: move buttons under graph property and include sequence events

---

docs/static/schemas/draft/2-0-0/application.d.ts
docs/static/schemas/draft/2-0-0/application.schema.json
schemas/applications/CHANGELOG.md
schemas/applications/schema/application.schema.json
schemas/applications/schema/frames.schema.json
schemas/applications/schema/graph.schema.json

- https://github.com/aica-technology/api/issues/147
As referenced in the original design spec, this adds two (non-breaking) enhancements to the draft schema, after which I would declare it ready to release as version 2-0-0.
Frames are quite simple to define:
```yaml
frames:
target:   # reference frame is "world" by default
position:
x: 0.5
y: 0.0
z: 1.0
orientation:
w: 1.0
x: 0.0
y: 0.0
z: 0.0
offset:
reference_frame: target
position:
x: 0.5
y: 0.0
z: 1.0
orientation:
w: 1.0
x: 0.0
y: 0.0
z: 0.0
```
The edge path information is stored under `graph: edges: [edge_id]: path`. By including the `path` sub-property, this leaves room for future expansion, for example to customize the position or content of an edge label. In practice it would look like this:
```yaml
graph:
positions:
on_start:
x: …
```

feat(schema): add frames and graph edge information

---

python/CHANGELOG.md
python/README.md
python/pyproject.toml
python/src/aica_api/client.py

This PR updates the python API client to the most recently available api endpoints. I'm not 100% sure if I miss some decorators for `@_requires_api_version('>=X.Y.Z')` or `@deprecated` or if we can even fully remove the deprecated endpoint, but appreciate if you give this a thought yourself. Thanks

feat: update python api client

---

schemas/parameters/schema/encoded_state_type.schema.json

I noticed that `joint_accelerations` was missing from the encoded state types in the schema. Along with that, we can also add the new IO states.
Because of the way the parameters and signals subschemas are versioned (or rather, not versioned), this has to be released to main before the component and controller descriptions can be tagged with a new version increment.

feat: add missing encoded state types from clproto

---

python/CHANGELOG.md
python/README.md
python/pyproject.toml

- #212 
Here I update the documentation for the API client and update the version to be released as v3.1.0

release(client): v3.1.0

---

schemas/applications/CHANGELOG.md
schemas/applications/schema/hardware.schema.json

- https://github.com/aica-technology/core-backend/issues/426
This PR solves the issue by adding 2 new options in the hardware section of the schema. This way, we can now define a `tf_prefix` and `reference_frame` that can be internally parsed as part of the hardware.

feat(schema): add custom tf prefix and reference frame options in hardware schema

---

schemas/applications/schema/frames.schema.json

Working on a demo, we realized that we are being super restrictive with frame names in the YAML. It is for example not possible to publish a frame "test" in reference frame "UR" just because we dont allow capital letters. I quickly checked with TF, it seems that they allow any character in their frame names, I guess we should just allow numbers, letters, underscore and maybe the dash as well. Would release that as 2-0-4.

fix(schema): less restrictive frame names

---

schemas/applications/CHANGELOG.md
schemas/applications/schema/common/events/set.schema.json
schemas/applications/schema/common/parameters.schema.json
schemas/applications/schema/frames.schema.json

- #246 
This PR solves the issue by relaxing the pattern properties of for parameter names. Now, numbers and capital letters are allowed anywhere in the name - also at the beginning. Also, there can be dots and dashes apart from the underscore. The same change was applied to frames, PR #235 was not good. It's not a problem since this change was not released yet.

feat(schema): more permissive names for frames and parameters
